In [1]:
import numpy as np

In [3]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [5]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
a = np.tile(np.arange(1,4,1), (1,2))

In [21]:
a

array([[1, 2, 3, 1, 2, 3]])

In [22]:
a.shape

(1, 6)

In [23]:
a

array([[1, 2, 3, 1, 2, 3]])

In [26]:
a[:, np.newaxis].shape

(1, 1, 6)

In [29]:
b=np.array([[1,2],[3,4]])

In [30]:
b.shape

(2, 2)

In [31]:
b[:]

array([[1, 2],
       [3, 4]])

In [33]:
b[:, np.newaxis], b[: np.newaxis].shape

(array([[[1, 2]],
 
        [[3, 4]]]),
 (2, 2))

In [34]:
c = np.array([1,2,3])

In [35]:
c.shape

(3,)

In [36]:
c[:, np.newaxis], c[:, np.newaxis].shape

(array([[1],
        [2],
        [3]]),
 (3, 1))

In [37]:
d = np.array([4,1,5,2,0])

In [38]:
np.sort(d)

array([0, 1, 2, 4, 5])

In [39]:
np.argsort(d)

array([4, 1, 3, 0, 2])

In [49]:
e = np.array([[3,1,2], [0,12,11]])

In [50]:
e.shape

(2, 3)

In [51]:
e

array([[ 3,  1,  2],
       [ 0, 12, 11]])

In [52]:
e.sort(axis=0)

In [53]:
e

array([[ 0,  1,  2],
       [ 3, 12, 11]])

In [54]:
e = np.array([[3,1,2], [0,12,11]])

In [55]:
e.sort(axis=1)

In [57]:
e

array([[ 1,  2,  3],
       [ 0, 11, 12]])

In [58]:
e = np.array([[3,1,2], [0,12,11]])

In [59]:
np.argsort(e)

array([[1, 2, 0],
       [0, 2, 1]])